### ISSUE TITLE
This is COOL !!!

### ISSUE THREAD

**Issue by Coder-X15** [swr06/Minecraft#8]
This is a cool project !! I ran the .exe file and whoa, it runs on my low-end PC as well ( 4GB RAM, 4th gen Intel Pentium [1.7GHz])! The smooth running of the game is worthy of a big round of applause. I tried a Python version by someone, but yours fare better than that guy's.

The only things that made me a bit disappointed:
* I can't change my controls to a more comfortable configuration, like the arrow keys instead of WASD keys.
* It doesn't have mobs. It will be cool if you add them! (maybe you were trying to make the Minecraft with creative mode only; in that case, sorry).
* The clouds didn't seem much like those in Minecraft, but yes, that is not of very much concern ':D
* If players can see their hands etc. as it would be in the real Minecraft, it will be cool. Also, menus for crafting and all that will surely add to the beauty of the game.
* I dunno what I got to do with the following recurring error that came in the window of the executable file, so maybe you can edit it:
```
OpenGL Error in Line 86 and in File : Core\Renderer\Renderer.cpp
        Error : INVALID_OPERATION
```
* I would like to have the HUD (where we see the materials at hand , lives, armour, etc.) seen as well, and I have no idea how to toggle it.

If these are added, then I say that this project's gonna be damn cool!!

I feel proud of my fellow Indian!!

**Comment by swr06** [comment]
Haha thanks! I dont really work on this project anymore :( 
I'm currently working on 2 new voxel engines, one path traced and the other one rasterized and aims at realism! L(
I do plan on adding gameplay to it at some point tho :)
