### ISSUE TITLE
How to build this game on android and ios

### ISSUE THREAD

**Issue by takaaptech** [swr06/Minecraft#9]
Hi @swr06 
This game run smooth and I want to build on an android or ios device
Please support me on how to config building this game on android and ios
Thank you so much!

**Comment by swr06** [comment]
Ah, I'm afraid that it's not possible to build it for ios and android as I used OpenGL 3.3 for this project, whereas, android and ios need OpenGL ES.

**Comment by takaaptech** [comment]
Hi @swr06 
Thank you for the detailed explanation!
If you have a chance, please support mobile device as a fallback to OpenGL ES and Vulkan

**Comment by swr06** [comment]
I've mostly stopped development on this project. I'm currently working on a path traced voxel engine, rasterized voxel engine and a 3D engine. If I were to ever return to this project, I'll certainly look into what you told.
